// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyARmi9JA-qargri8P_SZciAIsaa8zzx4sQ",
      authDomain: "auth-147ed.firebaseapp.com",
      projectId: "auth-147ed",
      storageBucket: "auth-147ed.appspot.com",
      messagingSenderId: "823250206272",
      appId: "1:823250206272:web:e716519eff6f85c938a9a5"
    );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnqnzNEIyDTrusRlAU77-2zfGu6Fzc7nM',
    appId: '1:823250206272:android:75f9542ee1e1c7fe38a9a5',
    messagingSenderId: '823250206272',
    projectId: 'auth-147ed',
    storageBucket: 'auth-147ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Qr4g88SFKhkvKK8ADfjGPr5dBWB2Imk',
    appId: '1:823250206272:ios:a9dcb1a1b6669ffe38a9a5',
    messagingSenderId: '823250206272',
    projectId: 'auth-147ed',
    storageBucket: 'auth-147ed.appspot.com',
    iosBundleId: 'com.example.firebaseSignin',
  );
}
